### ISSUE TITLE
ReferenceError: hostClients is not defined

### ISSUE THREAD

**Issue by mikaelkundert** [Marak/node_mailer#30]
Hi! I'm getting an error "ReferenceError: hostClients is not defined":

```
/.../node_modules/mailer/lib/node_mailer.js:68
     delete hostClients[options.user];
     ^
ReferenceError: hostClients is not defined
    at SMTPClient.<anonymous> (/.../node_modules/mailer/lib/node_mailer.js:68:6)
    at SMTPClient.emit (events.js:61:17)
    at SMTPClient._flushMessages (/.../node_modules/mailer/node_modules/nodemailer/lib/smtp.js:146:14)
    at Object.callback (/.../node_modules/mailer/node_modules/nodemailer/lib/smtp.js:235:22)
    at SMTPClient._dataListener (/.../node_modules/mailer/node_modules/nodemailer/lib/smtp.js:468:20)
    at SMTPClient.<anonymous> (/.../node_modules/mailer/node_modules/nodemailer/lib/smtp.js:643:14)
    at Socket.<anonymous> (native)
    at Socket.emit (events.js:64:17)
    at Socket._onReadable (net.js:676:14)
    at IOWatcher.onReadable [as callback] (net.js:177:10)
```

I just tried without SMTP auth and tried with my local ISP:

``` javascript
email.send({
  ssl: false,
  host : "smtp.saunalahti.fi",              // smtp server hostname
  port : 587,                     // smtp server port
  domain : "[127.0.0.1]",            // domain used by client to identify itself to server
  to : "bradley.meck@gmail.com",
  from : "bradley.meck@gmail.com",
  subject : "node_mailer test email",
  reply_to:"bradley@bradleymeck.com",
  body: "Hello! This is a test of the node_mailer."
});
```

**Comment by mikaelkundert** [comment]
Fix confirmed, thanks o/
