### ISSUE TITLE
Fails with nodemailer 0.2.0

### ISSUE THREAD

**Issue by pacovell** [Marak/node_mailer#41]
SMTPClient is removed from nodemailer 0.2.0, causing havoc.

**Comment by cojohn** [comment]
I believe I'm having problems with the recent update too!

TypeError: undefined is not a function
    at CALL_NON_FUNCTION_AS_CONSTRUCTOR (native)
    at SMTPClientPool.addClient (/Users/chris/node_modules/mailer/lib/node_mailer.js:38:44)
    at Object.node_mail as send (/Users/chris/node_modules/mailer/lib/node_mailer.js:100:10)

**Comment by aseemk** [comment]
+1

@gasi and I ran into this too. An easy short-term fix is to tighten the dependency in package.json to require "0.1.x >= 0.1.10" instead of just ">= 0.1.10". This is a best practice anyway w.r.t. semver anyway -- 0.1 to 0.2 means breaking changes.

Thanks in advance for fixing this.

**Comment by tcha-tcho** [comment]
+1
I did try to use a old version but "Error: 503 Already authenticated", I gonna try to downgrade all dependecies :(

**Comment by aseemk** [comment]
@tcha-tcho, the way we worked around this was: in _your_ package.json, put your own explicit "nodemailer" dependency for "0.1.x", npm uninstall nodemailer, then re-npm install/link/bundle/whatever your project.

Important: this nodemailer dependency needs to be _before_ your regular "mailer" dependency, so that the 0.1.x version of nodemailer gets installed, and then this project's nodemailer dependency is already met.

Hope that helps.

**Comment by tcha-tcho** [comment]
@aseemk hi, humm Im testing versions and don't think seems to be a nodemailer problem... It seems to be a mailer problem.... 

mailer has nodemailer as dependency? I did fall back the version of mailer to 0.4.x and all works again... even with nodemailer 2.0 activated ... strange

**Comment by balupton** [comment]
fix: https://github.com/Marak/node_mailer/pull/43

**Comment by andris9** [comment]
I'm the author of nodemailer. With 0.2.0 there was a change that introduced ability to use different backends for sending mail besides SMTP (like Amazon SES etc) and thus SMTPClient was hidden under a engine selection layer. I'm not very familiar with node_mailer and how it actually uses nodemailer so I wasn't able to foresee the impact to it from the change. Sorry for that.

**Comment by aseemk** [comment]
[deleted] Oops, meant to comment this on the pull request.
