### ISSUE TITLE
crash: hostClients is not defined

### ISSUE THREAD

**Issue by defunctzombie** [Marak/node_mailer#51]
In /lib/node_mailer.js:68

the hostClients variable is not in scope here.

**Comment by emilioastarita** [comment]
More info: 
ReferenceError: hostClients is not defined
    at SMTPClient.<anonymous> (/var/www/truco/node_modules/mailer/lib/node_mailer.js:68:6)
    at SMTPClient.emit (events.js:61:17)
    at SMTPClient._flushMessages (/var/www/truco/node_modules/mailer/node_modules/nodemailer/lib/smtp.js:146:14)
    at Object.callback (/var/www/truco/node_modules/mailer/node_modules/nodemailer/lib/smtp.js:235:22)
    at SMTPClient._dataListener (/var/www/truco/node_modules/mailer/node_modules/nodemailer/lib/smtp.js:468:20)
    at SMTPClient.<anonymous> (/var/www/truco/node_modules/mailer/node_modules/nodemailer/lib/smtp.js:642:14)
    at CleartextStream.<anonymous> (native)
    at CleartextStream.emit (events.js:64:17)
    at CleartextStream._push (tls.js:299:12)
    at SecurePair.cycle (tls.js:577:20)

**Comment by travisperson** [comment]
Looks like it was a copy and paste from addClient

The below is a quick fix (at least its working for me)

NOTES
hostClient => hostpool
options      => message.SERVER

```
SMTPClientPool.prototype.send = function send(message, callback) {
  var hostpool = this.servers[message.SERVER.host]
  if(!hostpool) hostpool = {};
  var client = hostpool[message.SERVER.user]
  if(!client) {
    client = hostpool[message.SERVER.user] = new SMTPClient(message.SERVER.host,message.SERVER.port,message.SERVER);
    client.on("close",function() {
      if(client == hostpool[message.SERVER.user]) {
          //only because this could be crazy long lived and dynamic
          delete hostpool[message.SERVER.user];
          if(Object.keys(hostpool).length == 0) {
            delete pool.servers[host]
          }
        }
    })
    client.on("empty",function(){
     delete hostpool[message.SERVER.user];
     client.close();})
  }
  client.sendMail(message,callback);
  client.on('error', callback);
}
```

**Comment by dobesv** [comment]
That fix worked for me, thanks!

For some reason this error only showed up on production and not in my dev/staging environments.  Strange, I guess the "empty" event doesn't always get called.  Maybe it depends on the mailserver?

**Comment by muratmat** [comment]
Same bug here, the fix worked but I'm wondering why you didn't change it in the official npm release...

**Comment by marook** [comment]
same issue here... would be cool to have a new npm release :-)

btw... travisperson's solution works for me.

**Comment by jdponomarev** [comment]
same here, quick fix works for me too.

**Comment by dmportella** [comment]
please update npm package

**Comment by jfgrossi** [comment]
is the npm package fixed for this issue?
