### ISSUE TITLE
Error in lineWrap() - make it optional perhaps?

### ISSUE THREAD

**Issue by coopernurse** [Marak/node_mailer#6]
Hi,

I'm using node-mailer 0.4.1 via npm

With some message bodies I'm getting this error in lineWrap()

TypeError: Cannot read property 'input' of null
    at Object.lineWrap (/usr/local/lib/node/.npm/mailer/0.4.1/package/lib/node_mailer.js:191:175)
    at Object.<anonymous> (/usr/local/lib/node/.npm/mailer/0.4.1/package/lib/node_mailer.js:166:28)
    at Object.send (/usr/local/lib/node/.npm/mailer/0.4.1/package/lib/node_mailer.js:230:12)
    at Object.sendEmail (../lib/email.js:100:16)

If I comment out line 166 I'm good to go.  I'd help patch this but that lineWrap code is pretty mystical.  

Thanks

-- James

**Comment by Marak** [comment]
The lineWrap code is mystical, agreed. :-D

Let's make this optional for now.

**Comment by Marak** [comment]
this should be resolved in 0.4.3. 

we have a new ( more sane ) lineWrap, and it's configurable. let me know if you have any more issues.
