### ISSUE TITLE
TypeError: Cannot call method 'match' of null

### ISSUE THREAD

**Issue by nagyv** [Marak/node_mailer#66]
I've just installed node_mailer, and trying to use it with a simple, local smtp connection served using python

```
$ python -m smtpd -n -c DebuggingServer localhost:1025
```

These are the options I call mailer.send with:

```
> config.email
{ host: 'localhost',
  port: 1025,
  domain: 'localhost',
  from: 'me@local.host',
  authentication: 'login',
  username: 'test',
  password: 'test',
  to: 'me@example.com',
  subject: 'MySubject',
  body: 'MyBody' }
> mailer.send(config.email, function(err, resp) {console.log(err, resp);})
undefined
> 
/home/akasha/workspace/status/playground/node_modules/mailer/node_modules/nodemailer/lib/smtp.js:572
        if(data.match(/PIPELINING/i)){
                ^
TypeError: Cannot call method 'match' of null
    at SMTPClient.<anonymous> (/home/akasha/workspace/status/playground/node_modules/mailer/node_modules/nodemailer/lib/smtp.js:572:17)
    at Object.callback (native)
    at SMTPClient._dataListener (/home/akasha/workspace/status/playground/node_modules/mailer/node_modules/nodemailer/lib/smtp.js:466:20)
    at SMTPClient.<anonymous> (/home/akasha/workspace/status/playground/node_modules/mailer/node_modules/nodemailer/lib/smtp.js:642:14)
    at Socket.<anonymous> (native)
    at Socket.emit (events.js:67:17)
    at TCP.onread (net.js:347:14)
```

What do I miss in this setup?

**Comment by andris9** [comment]
The server you are using does not support EHLO command and there's a bug with the older [Nodemailer](https://github.com/andris9/Nodemailer) version which node_mailer is using regarding HELO support. So it is not actually node_mailer issue.
